version: "3.9"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports: 
      - "127.0.0.1:9090:9090"
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
      - 'prometheus-metrics:/prometheus_data'
  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    volumes:
      - './proc:/host/proc'
      - './sys:/host/sys'
      - './rootfs:/rootfs'
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3011:3000"
volumes:
  prometheus-metrics: {}